package com.decoy.core

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

class CryptoTest {

    @Test
    fun `env var takes precedence over the key file`(@TempDir tmp: File) {
        File(tmp, ".decoy").mkdirs()
        File(tmp, KEY_RELATIVE_PATH).writeText("file-key")
        val key = loadKey(tmp, mapOf("DECOY_ENCRYPTION_KEY" to "env-key"))
        assertEquals("env-key", key)
    }

    @Test
    fun `falls back to the key file when no env var is set`(@TempDir tmp: File) {
        File(tmp, ".decoy").mkdirs()
        File(tmp, KEY_RELATIVE_PATH).writeText("file-key")
        assertEquals("file-key", loadKey(tmp, emptyMap()))
    }

    @Test
    fun `returns null when neither exists`(@TempDir tmp: File) {
        assertNull(loadKey(tmp, emptyMap()))
    }

    @Test
    fun `decrypts an ACTUAL Python-produced token (real cross-language interop)`() {
        // This exact key+token pair was generated by a real, separate
        // `cryptography.fernet.Fernet` call in Python (not by any JVM
        // code -- verified in the same interop check used for the VS
        // Code extension's equivalent test), encrypting
        // '{"format_version": 1, "entries": [{"field": "EMAIL"}]}'.
        // Decrypting it here with fernet-java8 proves actual
        // cross-language compatibility, not just that this JVM code can
        // read its own writes.
        val pythonKey = "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4="
        val pythonToken =
            "gAAAAABqlGBLthNuPt8KHSY_IYVdP85dgOsTPvi5LIl_Nq_8NS6nWvX7OLU2m1lUEgxa6gZoT1mpuchdW2IlT3b7" +
                "W384qKVUS7kqMOlR_wTrXtPVNG89kbXIn-yN8RzBsRLvhylXAsHueR7Lr4Dm0hrqT9ZGzx7eTg=="

        val decoded = decryptToken(pythonToken, pythonKey)
        assertEquals("""{"format_version": 1, "entries": [{"field": "EMAIL"}]}""", decoded)
    }

    @Test
    fun `a token this JVM encrypts round-trips through its own decrypt`() {
        // Bidirectional interop (JVM-encrypted token decrypted correctly
        // by Python) was verified manually against a real `python3
        // -c "cryptography.fernet..."` call during development (see the
        // Phase 9 summary) -- not repeatable here since this test suite
        // has no Python runtime available. This test covers the JVM
        // round-trip half automatically on every run.
        val key = "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4="
        val token = encryptToken("hello world", key)
        assertEquals("hello world", decryptToken(token, key))
    }

    @Test
    fun `decryptToken fails safe to null on a corrupted token`() {
        assertNull(decryptToken("not a valid fernet token", "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4="))
    }

    @Test
    fun `decryptToken fails safe to null with the wrong key`() {
        val key1 = "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4="
        val key2 = "b3RoZXJrZXlvdGhlcmtleW90aGVya2V5b3RoZXJrZXk="
        val token = encryptToken("secret", key1)
        assertNull(decryptToken(token, key2))
    }
}
