import * as fs from "fs";
import * as os from "os";
import * as path from "path";

import { clearAuditAll, clearAuditSession, groupByRequest, loadKey, readAuditLog, writeAuditLog } from "./auditLog";
import { AuditEntry, AuditLogFile } from "./types";

function makeTmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "decoy-audit-test-"));
}

function makeEntry(overrides: Partial<AuditEntry> = {}): AuditEntry {
  return {
    id: "id-1",
    request_id: "req-1",
    session_id: "session-1",
    timestamp: "2026-08-30T21:15:03.482Z",
    source: "prompt_text",
    field: "EMAIL",
    decision: "masked",
    reason: "matched EMAIL regex",
    layer: "regex",
    ...overrides,
  };
}

describe("loadKey", () => {
  it("prefers DECOY_ENCRYPTION_KEY env var over the key file", () => {
    const root = makeTmpDir();
    fs.mkdirSync(path.join(root, ".decoy"));
    fs.writeFileSync(path.join(root, ".decoy", "vault.key"), "file-key");
    const key = loadKey(root, { DECOY_ENCRYPTION_KEY: "env-key" } as NodeJS.ProcessEnv);
    expect(key).toBe("env-key");
  });

  it("falls back to the key file when no env var is set", () => {
    const root = makeTmpDir();
    fs.mkdirSync(path.join(root, ".decoy"));
    fs.writeFileSync(path.join(root, ".decoy", "vault.key"), "file-key");
    const key = loadKey(root, {} as NodeJS.ProcessEnv);
    expect(key).toBe("file-key");
  });

  it("returns null when neither exists", () => {
    const root = makeTmpDir();
    expect(loadKey(root, {} as NodeJS.ProcessEnv)).toBeNull();
  });
});

describe("readAuditLog / writeAuditLog round trip", () => {
  it("reads back exactly what was written, encrypted at rest", () => {
    const root = makeTmpDir();
    const env = { DECOY_ENCRYPTION_KEY: "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4=" } as NodeJS.ProcessEnv;
    const data: AuditLogFile = { format_version: 1, entries: [makeEntry()] };

    writeAuditLog(root, data, env);
    const rawBytes = fs.readFileSync(path.join(root, ".decoy", "audit.enc"), "utf8");
    expect(rawBytes).not.toContain("EMAIL");
    expect(() => JSON.parse(rawBytes)).toThrow();

    const readBack = readAuditLog(root, env);
    expect(readBack).toEqual(data);
  });

  it("reads an ACTUAL Python-produced token correctly (real cross-language interop)", () => {
    // This exact key/token pair was generated by a real, separate
    // `cryptography.fernet.Fernet` call in Python (not by this TS code --
    // see the interop check that produced it), encrypting
    // '{"format_version": 1, "entries": [{"field": "EMAIL"}]}'. Decrypting
    // it here with the `fernet` npm package proves actual cross-language
    // compatibility, not just that this file can read its own writes.
    const root = makeTmpDir();
    const pythonKey = "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4=";
    const pythonToken =
      "gAAAAABqlGBLthNuPt8KHSY_IYVdP85dgOsTPvi5LIl_Nq_8NS6nWvX7OLU2m1lUEgxa6gZoT1mpuchdW2IlT3b7" +
      "W384qKVUS7kqMOlR_wTrXtPVNG89kbXIn-yN8RzBsRLvhylXAsHueR7Lr4Dm0hrqT9ZGzx7eTg==";
    fs.mkdirSync(path.join(root, ".decoy"), { recursive: true });
    fs.writeFileSync(path.join(root, ".decoy", "audit.enc"), pythonToken, "utf8");

    const result = readAuditLog(root, { DECOY_ENCRYPTION_KEY: pythonKey } as NodeJS.ProcessEnv);
    // Note: this fixture's format_version:1 payload predates the
    // request_id/session_id/etc. fields being added to the fixture itself
    // (it's a minimal {"field": "EMAIL"} entry) -- readAuditLog doesn't
    // validate per-entry shape, only format_version, so this still proves
    // the decrypt+parse path works end-to-end across languages.
    expect(result.format_version).toBe(1);
    expect(result.entries).toHaveLength(1);
    expect((result.entries[0] as unknown as { field: string }).field).toBe("EMAIL");
  });

  it("fails safe to an empty log on a missing file", () => {
    const root = makeTmpDir();
    const result = readAuditLog(root, { DECOY_ENCRYPTION_KEY: "any-key" } as NodeJS.ProcessEnv);
    expect(result.entries).toEqual([]);
  });

  it("fails safe to an empty log on a corrupted file rather than throwing", () => {
    const root = makeTmpDir();
    fs.mkdirSync(path.join(root, ".decoy"));
    fs.writeFileSync(path.join(root, ".decoy", "audit.enc"), "not a valid fernet token");
    const result = readAuditLog(root, { DECOY_ENCRYPTION_KEY: "some-key" } as NodeJS.ProcessEnv);
    expect(result.entries).toEqual([]);
  });

  it("fails safe to an empty log with the wrong key rather than misreading garbage", () => {
    const root = makeTmpDir();
    const env1 = { DECOY_ENCRYPTION_KEY: "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4=" } as NodeJS.ProcessEnv;
    const env2 = { DECOY_ENCRYPTION_KEY: "b3RoZXJrZXlvdGhlcmtleW90aGVya2V5b3RoZXJrZXk=" } as NodeJS.ProcessEnv;
    writeAuditLog(root, { format_version: 1, entries: [makeEntry()] }, env1);
    const result = readAuditLog(root, env2);
    expect(result.entries).toEqual([]);
  });

  it("fails safe to an empty log on an unrecognized format_version", () => {
    const root = makeTmpDir();
    const env = { DECOY_ENCRYPTION_KEY: "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4=" } as NodeJS.ProcessEnv;
    writeAuditLog(root, { format_version: 999, entries: [makeEntry()] } as unknown as AuditLogFile, env);
    const result = readAuditLog(root, env);
    expect(result.entries).toEqual([]);
  });
});

describe("clearAuditSession / clearAuditAll", () => {
  const env = { DECOY_ENCRYPTION_KEY: "nhtXQTnXQzKW_0m_5r-ffK8dcl03BLSzJOOdmF8bDk4=" } as NodeJS.ProcessEnv;

  it("clearAuditSession only removes entries for that session", () => {
    const root = makeTmpDir();
    writeAuditLog(
      root,
      {
        format_version: 1,
        entries: [
          makeEntry({ id: "a", session_id: "session-a" }),
          makeEntry({ id: "b", session_id: "session-b" }),
        ],
      },
      env,
    );

    const removed = clearAuditSession(root, "session-a", env);
    expect(removed).toBe(1);

    const remaining = readAuditLog(root, env);
    expect(remaining.entries).toHaveLength(1);
    expect(remaining.entries[0].session_id).toBe("session-b");
  });

  it("clearAuditAll removes everything", () => {
    const root = makeTmpDir();
    writeAuditLog(
      root,
      { format_version: 1, entries: [makeEntry({ id: "a" }), makeEntry({ id: "b" })] },
      env,
    );

    const removed = clearAuditAll(root, env);
    expect(removed).toBe(2);
    expect(readAuditLog(root, env).entries).toEqual([]);
  });
});

describe("groupByRequest", () => {
  it("groups entries by request_id and sorts newest first", () => {
    const entries: AuditEntry[] = [
      makeEntry({ id: "1", request_id: "req-old", timestamp: "2026-01-01T00:00:00.000Z" }),
      makeEntry({ id: "2", request_id: "req-new", timestamp: "2026-06-01T00:00:00.000Z" }),
      makeEntry({ id: "3", request_id: "req-old", field: "PHONE", timestamp: "2026-01-01T00:00:00.001Z" }),
    ];
    const groups = groupByRequest(entries);
    expect(groups).toHaveLength(2);
    expect(groups[0].request_id).toBe("req-new");
    expect(groups[1].request_id).toBe("req-old");
    expect(groups[1].entries).toHaveLength(2);
  });
});
